### ISSUE TITLE
Merge with container-suseconnect?

### ISSUE THREAD

**Issue by dcermak** [SUSE/connect-ng#127]
https://github.com/SUSE/container-suseconnect is a zypper plugin for containers that will reuse the existing credentials from a SLE host and register your container automatically. Unfortunately, the project is more or less unmaintained now, but we are relying on it for our BCI offerings.

Would it be possible to merge container-suseconnect into connect-ng? This would hopefully allow to add some quality of life improvements to container-suseconnect, like automatically registering your container from environment variables without relying on a patched docker installation.

**Comment by djoreilly** [comment]
Yes, that's probably a good idea. 

I had a look at container-suseconnect and it does not register the container. It uses the credentials of the host (or some other registered SLES host) to get the regcode, and then with that it can get the repos for zypper.

I don't think the patched docker is needed anymore as docker now has `build --secret` as described here https://github.com/SUSE/container-suseconnect#building-images-on-non-sle-distributions .  This will also put the credentials in `/run/secrets/` 

If env vars were used to pass secrets, wouldn't they end up in the built image?

**Comment by dcermak** [comment]
> I don't think the patched docker is needed anymore as docker now has `build --secret` as described here https://github.com/SUSE/container-suseconnect#building-images-on-non-sle-distributions . This will also put the credentials in `/run/secrets/`

The patched version of docker is not necessary for being able to pass secrets. It is however necessary to **automatically** pass the secret on a sles host.

> If env vars were used to pass secrets, wouldn't they end up in the built image?

Hm, that's correct. Depending on your use case that might be ok, but I agree that we probably should not implement this by default.

**Comment by dcermak** [comment]
@djoreilly @skazi0 @mssola Any thoughts whether and how we can move this forward?

**Comment by mssola** [comment]
I can see the appeal to merge both these projects. That being said, there is not much code that could be shared between both these projects, even if their naming might hint otherwise. Indeed, relying on an unmaintained project is troublesome, and so I can see why we would like to do something about this situation. However, I also worry that a `suseconnect-ng` which also has the code from `container-suseconnect` might become a bit of a monster, since their end goal is more different as you might think at first, and the UX might not be that appealing to a customer.

All that being said, the main problem I see here is "who is maintaining this project". That is, if we merge it with `suseconnect-ng`, then SCC will have to maintain this piece of software that was developed *outside* of SCC. I can see why SCC should maintain `suseconnect-ng`, since it is a replacement of a project that we maintain anyways, but `container-suseconnect`, despite its naming, is a different thing: it's about sharing a bunch of files from the host into the container automatically so the container can go on as if it was the host. This has nothing to do with SCC in on itself, and it's more about how containers are to be managed. Thus, and don't get me wrong, I believe this should be maintained by someone at SUSE who works around managing containers, whoever that might be.

**Comment by felixsch** [comment]
I think its clear right now there is no further movement in this direction. I close this here for now and if there is another intensive to make this happen another issue can be opened! Thanks for clarifying Miquel!
